version: '2'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - /Users/velementsmount/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
     - "3000:3000"
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9999:9091
 
  
